# retain_graph

See discussions [here](https://discuss.pytorch.org/t/what-exactly-does-retain-variables-true-in-loss-backward-do/3508/12)

![](https://discuss.pytorch.org/uploads/default/optimized/2X/a/aace8d6020dc8652caf356257db5cc06fe793d42_2_1035x306.JPG)

`loss = loss1 + loss2; loss.backward()` does the same thing as `loss1.backward(retain_graph=True);loss2.backward()`

In [1]:
import torch

In [2]:
x = torch.Tensor([1, 2, 3]).requires_grad_()
y = x**2
loss1 = torch.mean(y)
z = torch.log(y)
loss2 = torch.mean(z)
loss1.backward()
#loss2.backward() # report error
print(x.grad)

tensor([0.6667, 1.3333, 2.0000])


In [3]:
x = torch.Tensor([1, 2, 3]).requires_grad_()
y = x**2
loss1 = torch.mean(y)
z = torch.log(y)
loss2 = torch.mean(z)
loss1.backward(retain_graph=True)
loss2.backward()
print(x.grad)

tensor([1.3333, 1.6667, 2.2222])


In [4]:
x = torch.Tensor([1, 2, 3]).requires_grad_()
y = x**2
loss1 = torch.mean(y)
z = torch.log(y)
loss2 = torch.mean(z)
loss = loss1 + loss2
loss.backward()
print(x.grad)

tensor([1.3333, 1.6667, 2.2222])
